---
- name: Import base image playbook
  import_playbook: base.yml

- name: Import Cobalt Strike and related tools playbook
  import_playbook: cobalt_strike.yml

- name: Import VNC playbook
  import_playbook: vnc.yml

- name: Import cloud-init playbook
  import_playbook: cloud_init.yml

- name: Import AWS playbook
  import_playbook: aws.yml
